name: Auto-Async

on:
  push:
  schedule:
    #自动同步：每天早上1点
    - cron:  0 17 * * *
  workflow_dispatch:
  watch:
    types: [started]

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Merge upstream
        run: |
          git config --global user.name 'laosan-xx'
          git config --global user.email 'xxhy1989@gmail.com'
          # 删除 git pull --unshallow 这一行
          git remote add upstream https://github.com/immortalwrt/homeproxy.git
          git fetch upstream
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
